In [1]:
import numpy as np 


In [ ]:


P = np.array([[0.5, 0.5, 0],
              [0.5, 0, 0.5],
              [0.5, 0, 0.5]])

eigval, eigvec = np.linalg.eig(np.transpose(P))
print(eigval)
print(eigvec)

s0 = np.array([1,0,0])
P4 = np.linalg.matrix_power(P,4)
r = np.matmul(s0, P4)
print(r)


[ 1.00000000e+00  4.86617333e-09 -4.86617332e-09]
[[-8.16496581e-01 -6.88180830e-09 -6.88180833e-09]
 [-4.08248290e-01 -7.07106778e-01  7.07106785e-01]
 [-4.08248290e-01  7.07106785e-01 -7.07106778e-01]]
[0.5  0.25 0.25]
<class 'dict'>
